[package]
name = "sotpal_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "0.2", features = ["full"] }
rand = "0.8.5"
indexmap = "1.9.1"
telegram-bot = "0.8.0"
futures = "0.3"
openssl = "0.10.41"

[features]
terminal = []
telegram = ['openssl/vendored']
