name: Rust

on:
  push:
    branches: [ "**" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Build Terminal
      run: cargo build --verbose --features terminal
    - name: Build Telegram
      run: cargo build --verbose --features telegram
    - name: Run tests
      run: cargo test --verbose
    - name: Test Terminal
      run: cargo test --verbose --features terminal
    - name: Test Telegram
      run: cargo test --verbose --features telegram

  tg-release:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v3
    - name: Install ARM target
      run: rustup target add armv7-unknown-linux-gnueabihf && sudo apt install gcc-arm-linux-gnueabihf
    - name: Release Build
      run: cargo build --release --features telegram --target armv7-unknown-linux-gnueabihf
    - name: Save Artifacts
      uses: actions/upload-artifact@v3
      if: success()
      with:
        name: tg-release
        path: target/armv7-unknown-linux-gnueabihf/release/sotpal_rust
        retention-days: 2